/* AMD K8 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
2008 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8

/* 2200 MHz Opteron / rev A / 1024 Kibyte cache / socket 940 */

/* Generated by tuneup.c, 2008-10-04, gcc 3.4 */

#define MUL_KARATSUBA_THRESHOLD          28
#define MUL_TOOM3_THRESHOLD              97

#define SQR_BASECASE_THRESHOLD           28
#define SQR_KARATSUBA_THRESHOLD          87
#define SQR_TOOM3_THRESHOLD             105

#define MULLOW_BASECASE_THRESHOLD         4
#define MULLOW_DC_THRESHOLD              28
#define MULLOW_MUL_N_THRESHOLD          260

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 88
#define POWM_THRESHOLD                  185

#define DC_DIV_QR_THRESHOLD              42
#define DC_DIVAPPR_Q_THRESHOLD          228
#define DC_DIV_Q_THRESHOLD              222
#define DC_BDIV_QR_THRESHOLD             42
#define DC_BDIV_Q_THRESHOLD              10
#define DIVEXACT_JEB_THRESHOLD           50

#define MATRIX22_STRASSEN_THRESHOLD      22
#define HGCD_THRESHOLD                  134
#define GCD_DC_THRESHOLD                453
#define GCDEXT_DC_THRESHOLD             661
#define JACOBI_BASE_METHOD                1

#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */

#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             15
#define GET_STR_PRECOMPUTE_THRESHOLD     26
#define SET_STR_DC_THRESHOLD            422
#define SET_STR_PRECOMPUTE_THRESHOLD   2583

#define MUL_FFT_TABLE  { 400, 800, 2112, 3840, 11264, 36864, 0 }
#define MUL_FFT_MODF_THRESHOLD          560
#define MUL_FFT_THRESHOLD              6528

#define SQR_FFT_TABLE  { 400, 928, 1728, 4352, 11264, 28672, 0 }
#define SQR_FFT_MODF_THRESHOLD          432
#define SQR_FFT_THRESHOLD              4736

#define MUL_FFT_TABLE2 {{1,4}, {337,5}, {673,6}, {1729,7}, {5633,8}, {11009,9}, {11777,8}, {13057,9}, {13313,8}, {13569,9}, {15873,8}, {16641,9}, {22017,10}, {23553,9}, {29697,10}, {31745,9}, {36353,10}, {40961,9}, {43009,10}, {48129,9}, {50689,10}, {53249,11}, {63489,10}, {72705,9}, {73729,11}, {75777,10}, {87041,9}, {87553,10}, {89089,11}, {96257,10}, {114689,11}, {116737,12}, {126977,11}, {129025,10}, {141313,11}, {161793,10}, {171521,11}, {227329,12}, {258049,11}, {326145,12}, {389121,11}, {MP_SIZE_T_MAX,0}}

#define SQR_FFT_TABLE2 {{1,4}, {305,5}, {609,6}, {1601,7}, {4609,8}, {11009,9}, {11777,8}, {12545,9}, {13825,10}, {15361,9}, {15873,8}, {16641,9}, {22017,10}, {23553,9}, {28161,11}, {30721,10}, {31745,9}, {36353,10}, {39937,9}, {42497,10}, {56321,11}, {63489,10}, {79873,11}, {97281,10}, {100353,8}, {100609,10}, {105729,12}, {126977,11}, {129025,10}, {130049,11}, {131585,10}, {140033,11}, {163841,10}, {171009,11}, {204801,12}, {208897,11}, {225281,12}, {258049,11}, {260097,10}, {263169,9}, {MP_SIZE_T_MAX,0}}

#define INV_NEWTON_THRESHOLD             47
#define BINV_NEWTON_THRESHOLD            18
