/* Intel P55 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002 Free Software Foundation,
Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */


#define BITS_PER_MP_LIMB 32
#define BYTES_PER_MP_LIMB 4


/* For mpn/x86/pentium/mod_1.asm */
#define COUNT_LEADING_ZEROS_NEED_CLZ_TAB


/* 166MHz P55, gcc 2.95.2 */

/* Generated by tuneup.c, 2001-11-28, gcc 2.95 */

#define MUL_KARATSUBA_THRESHOLD       16
#define MUL_TOOM3_THRESHOLD          105

#define SQR_BASECASE_THRESHOLD         0
#define SQR_KARATSUBA_THRESHOLD       22
#define SQR_TOOM3_THRESHOLD          149

#define DIV_SB_PREINV_THRESHOLD            4
#define DIV_DC_THRESHOLD                  44
#define POWM_THRESHOLD                62

#define GCD_ACCEL_THRESHOLD            3
#define GCDEXT_THRESHOLD              17

#define USE_PREINV_MOD_1               1  /* (native) */
#define DIVREM_2_THRESHOLD             0
#define DIVEXACT_1_THRESHOLD           0
#define MODEXACT_1_ODD_THRESHOLD       0

#define MUL_FFT_TABLE  { 464, 928, 1920, 4608, 14336, 40960, 0 }
#define MUL_FFT_MODF_THRESHOLD       440
#define MUL_FFT_THRESHOLD           3840

#define SQR_FFT_TABLE  { 496, 1120, 2176, 5632, 14336, 40960, 0 }
#define SQR_FFT_MODF_THRESHOLD       424
#define SQR_FFT_THRESHOLD           3840
