/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002, 2003, 2004 Free Software
Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
for more details.

You should have received a copy of the GNU Lesser General Public License along
with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8

/* These values were measured on a PA8500 using the system compiler version
   B.11.11.04.  Measurements on PA8000 with system compiler version A.10.32.30
   give very similar values, GCC 3.1 will probably give somewhat different
   results (earlier GCC versions do not support HPPA in 64-bit mode).  */

/* Generated by tuneup.c, 2004-02-06, system compiler */

#define MUL_KARATSUBA_THRESHOLD          23
#define MUL_TOOM3_THRESHOLD             101

#define SQR_BASECASE_THRESHOLD            5
#define SQR_KARATSUBA_THRESHOLD          60
#define SQR_TOOM3_THRESHOLD             113

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                123
#define POWM_THRESHOLD                  212

#define HGCD_THRESHOLD                  292
#define GCD_ACCEL_THRESHOLD               3
#define GCD_DC_THRESHOLD               1498
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             21
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_THRESHOLD             14423

#define MUL_FFT_TABLE  { 528, 1056, 2368, 4864, 9216, 36864, 0 }
#define MUL_FFT_MODF_THRESHOLD          360
#define MUL_FFT_THRESHOLD              1952

#define SQR_FFT_TABLE  { 528, 1184, 2624, 5376, 11264, 28672, 0 }
#define SQR_FFT_MODF_THRESHOLD          376
#define SQR_FFT_THRESHOLD              2592
