/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002, 2003, 2004, 2008, 2009
Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
for more details.

You should have received a copy of the GNU Lesser General Public License along
with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 64
#define BYTES_PER_MP_LIMB 8

/* 440MHz PA8200 */

/* Generated by tuneup.c, 2009-11-29, system compiler */

#define MUL_TOOM22_THRESHOLD             30
#define MUL_TOOM33_THRESHOLD            113
#define MUL_TOOM44_THRESHOLD            195

#define SQR_BASECASE_THRESHOLD            4
#define SQR_TOOM2_THRESHOLD              56
#define SQR_TOOM3_THRESHOLD             169
#define SQR_TOOM4_THRESHOLD             284

#define MUL_FFT_TABLE  { 336, 800, 1600, 2816, 7168, 20480, 81920, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          280
#define MUL_FFT_THRESHOLD              1664

#define SQR_FFT_TABLE  { 368, 800, 1728, 3328, 7168, 20480, 81920, 327680, 786432, 0 }
#define SQR_FFT_MODF_THRESHOLD          264
#define SQR_FFT_THRESHOLD              1792

#define MULLO_BASECASE_THRESHOLD          0  /* always */
#define MULLO_DC_THRESHOLD              111
#define MULLO_MUL_N_THRESHOLD          2764

#define MULMOD_BNM1_THRESHOLD            20

#define DC_DIV_QR_THRESHOLD             124
#define DC_BDIV_QR_THRESHOLD            150
#define DC_BDIV_Q_THRESHOLD             312
#define BINV_NEWTON_THRESHOLD           720
#define REDC_1_TO_REDC_N_THRESHOLD      106

#define MATRIX22_STRASSEN_THRESHOLD      11
#define HGCD_THRESHOLD                  236
#define GCD_DC_THRESHOLD                758
#define GCDEXT_DC_THRESHOLD             744
#define JACOBI_BASE_METHOD                2

#define DIVREM_1_NORM_THRESHOLD           0  /* always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define MOD_1_1_THRESHOLD             MP_SIZE_T_MAX  /* never */
#define MOD_1_2_THRESHOLD             MP_SIZE_T_MAX  /* never */
#define MOD_1_4_THRESHOLD             MP_SIZE_T_MAX  /* never */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             20
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           2008
#define SET_STR_PRECOMPUTE_THRESHOLD   4066
