/* IBM s370 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2001 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */


/* BITS_PER_MP_LIMB etc generated by configure */


/* Generated by tuneup.c, 2001-09-26, gcc 2.95 */

#define KARATSUBA_MUL_THRESHOLD       17
#define TOOM3_MUL_THRESHOLD          116

#define BASECASE_SQR_THRESHOLD         6
#define KARATSUBA_SQR_THRESHOLD       36
#define TOOM3_SQR_THRESHOLD          210

#define SB_PREINV_THRESHOLD            0
#define DC_THRESHOLD                  49
#define POWM_THRESHOLD                60

#define GCD_ACCEL_THRESHOLD            3
#define GCDEXT_THRESHOLD              19

#define DIVREM_1_NORM_THRESHOLD        0
#define DIVREM_1_UNNORM_THRESHOLD      6
#define MOD_1_NORM_THRESHOLD           0
#define MOD_1_UNNORM_THRESHOLD         4
#define USE_PREINV_MOD_1               1
#define DIVREM_2_THRESHOLD             0
#define DIVEXACT_1_THRESHOLD           0
#define MODEXACT_1_ODD_THRESHOLD       0

#define FFT_MUL_TABLE  { 368, 800, 1408, 3584, 10240, 40960, 0 }
#define FFT_MODF_MUL_THRESHOLD       384
#define FFT_MUL_THRESHOLD           2816

#define FFT_SQR_TABLE  { 368, 864, 1408, 3584, 10240, 40960, 0 }
#define FFT_MODF_SQR_THRESHOLD       384
#define FFT_SQR_THRESHOLD           2816
