/* IBM s370 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2001 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */


/* BITS_PER_MP_LIMB etc generated by configure */


/* Generated by tuneup.c, 2001-12-03, gcc 2.95 */

#define KARATSUBA_MUL_THRESHOLD       18
#define TOOM3_MUL_THRESHOLD          210

#define BASECASE_SQR_THRESHOLD         8
#define KARATSUBA_SQR_THRESHOLD       40
#define TOOM3_SQR_THRESHOLD          250

#define SB_PREINV_THRESHOLD            0
#define DC_THRESHOLD                  63
#define POWM_THRESHOLD                63

#define GCD_ACCEL_THRESHOLD            3
#define GCDEXT_THRESHOLD              28

#define DIVREM_1_NORM_THRESHOLD        0
#define DIVREM_1_UNNORM_THRESHOLD      5
#define MOD_1_NORM_THRESHOLD           0
#define MOD_1_UNNORM_THRESHOLD         4
#define USE_PREINV_MOD_1               0
#define DIVREM_2_THRESHOLD             0
#define DIVEXACT_1_THRESHOLD           0
#define MODEXACT_1_ODD_THRESHOLD       0

#define FFT_MUL_TABLE  { 432, 992, 1664, 4608, 14336, 40960, 0 }
#define FFT_MODF_MUL_THRESHOLD       448
#define FFT_MUL_THRESHOLD           3840

#define FFT_SQR_TABLE  { 400, 992, 1664, 4608, 10240, 40960, 0 }
#define FFT_MODF_SQR_THRESHOLD       416
#define FFT_SQR_THRESHOLD           3328
