/* Intel Pentium-4 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2019 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 32
#define GMP_LIMB_BYTES 4

/* 2600 MHz P4 Northwood */
/* FFT tuning limit = 0.5 M */
/* Generated by tuneup.c, 2019-10-01, gcc 8.2 */

#define MOD_1_NORM_THRESHOLD                 5
#define MOD_1_UNNORM_THRESHOLD              18
#define MOD_1N_TO_MOD_1_1_THRESHOLD          7
#define MOD_1U_TO_MOD_1_1_THRESHOLD          5
#define MOD_1_1_TO_MOD_1_2_THRESHOLD        13
#define MOD_1_2_TO_MOD_1_4_THRESHOLD         0  /* never mpn_mod_1s_2p */
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD      8
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 2  /* 4.58% faster than 1 */
#define DIV_QR_1_NORM_THRESHOLD             18
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD           MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD                 0  /* always (native) */
#define BMOD_1_TO_MOD_1_THRESHOLD           22

#define DIV_1_VS_MUL_1_PERCENT             368

#define MUL_TOOM22_THRESHOLD                30
#define MUL_TOOM33_THRESHOLD               133
#define MUL_TOOM44_THRESHOLD               204
#define MUL_TOOM6H_THRESHOLD               399
#define MUL_TOOM8H_THRESHOLD               608

#define MUL_TOOM32_TO_TOOM43_THRESHOLD     120
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     210
#define MUL_TOOM42_TO_TOOM53_THRESHOLD     191
#define MUL_TOOM42_TO_TOOM63_THRESHOLD     196
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     176

#define SQR_BASECASE_THRESHOLD               0  /* always (native) */
#define SQR_TOOM2_THRESHOLD                 48
#define SQR_TOOM3_THRESHOLD                169
#define SQR_TOOM4_THRESHOLD                396
#define SQR_TOOM6_THRESHOLD                  0  /* always */
#define SQR_TOOM8_THRESHOLD                882

#define MULMID_TOOM42_THRESHOLD             63

#define MULMOD_BNM1_THRESHOLD               15
#define SQRMOD_BNM1_THRESHOLD               19

#define MUL_FFT_MODF_THRESHOLD             660  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    660, 5}, {     22, 4}, {     45, 5}, {     28, 6}, \
    {     15, 5}, {     32, 6}, {     17, 5}, {     35, 6}, \
    {     19, 5}, {     39, 6}, {     23, 5}, {     48, 6}, \
    {     29, 7}, {     15, 6}, {     31, 7}, {     17, 6}, \
    {     37, 7}, {     19, 6}, {     40, 7}, {     21, 6}, \
    {     43, 7}, {     23, 6}, {     47, 7}, {     37, 8}, \
    {     19, 7}, {     43, 8}, {     23, 7}, {     49, 8}, \
    {     27, 7}, {     55, 8}, {     31, 7}, {     63, 8}, \
    {     43, 9}, {     23, 8}, {     55, 9}, {     31, 8}, \
    {     71, 9}, {     39, 8}, {     83, 9}, {     47, 8}, \
    {     99, 9}, {     55,10}, {     31, 9}, {     79,10}, \
    {     47, 9}, {     95,11}, {     31,10}, {     63, 9}, \
    {    135,10}, {     79, 9}, {    159,10}, {    111,11}, \
    {     63,10}, {    159,11}, {     95,10}, {    191,12}, \
    {     63,11}, {    127,10}, {    271,11}, {    159,10}, \
    {    335,11}, {    191,10}, {    399, 9}, {    799,10}, \
    {    415,11}, {    223,12}, {   4096,13}, {   8192,14}, \
    {  16384,15}, {  32768,16} }
#define MUL_FFT_TABLE3_SIZE 70
#define MUL_FFT_THRESHOLD                 6784

#define SQR_FFT_MODF_THRESHOLD             555  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    555, 5}, {     29, 6}, {     15, 5}, {     33, 6}, \
    {     17, 5}, {     35, 6}, {     19, 5}, {     39, 6}, \
    {     29, 7}, {     15, 6}, {     33, 7}, {     17, 6}, \
    {     36, 7}, {     19, 6}, {     39, 7}, {     23, 6}, \
    {     48, 7}, {     29, 8}, {     15, 7}, {     37, 8}, \
    {     19, 7}, {     43, 8}, {     23, 7}, {     49, 8}, \
    {     27, 7}, {     55, 8}, {     31, 7}, {     63, 8}, \
    {     43, 9}, {     23, 8}, {     55,10}, {     15, 9}, \
    {     31, 8}, {     67, 9}, {     39, 8}, {     79, 9}, \
    {     47, 8}, {     95, 9}, {     55,10}, {     31, 9}, \
    {     79,10}, {     47, 9}, {    103,11}, {     31,10}, \
    {     63, 9}, {    135,10}, {     79, 9}, {    159,10}, \
    {     95, 9}, {    191,10}, {    111,11}, {     63,10}, \
    {    143, 9}, {    287,10}, {    175,11}, {     95,10}, \
    {    191,12}, {     63,11}, {    127,10}, {    255, 9}, \
    {    511,10}, {    271, 9}, {    543,11}, {    159,10}, \
    {    351,11}, {    191,10}, {    399, 9}, {    799,10}, \
    {    415,11}, {    223,12}, {   4096,13}, {   8192,14}, \
    {  16384,15}, {  32768,16} }
#define SQR_FFT_TABLE3_SIZE 74
#define SQR_FFT_THRESHOLD                 4800

#define MULLO_BASECASE_THRESHOLD            13
#define MULLO_DC_THRESHOLD                  54
#define MULLO_MUL_N_THRESHOLD            13463
#define SQRLO_BASECASE_THRESHOLD            12
#define SQRLO_DC_THRESHOLD                  90
#define SQRLO_SQR_THRESHOLD               9513

#define DC_DIV_QR_THRESHOLD                 42
#define DC_DIVAPPR_Q_THRESHOLD             119
#define DC_BDIV_QR_THRESHOLD                52
#define DC_BDIV_Q_THRESHOLD                 95

#define INV_MULMOD_BNM1_THRESHOLD           11
#define INV_NEWTON_THRESHOLD               150
#define INV_APPR_THRESHOLD                 125

#define BINV_NEWTON_THRESHOLD              363
#define REDC_1_TO_REDC_N_THRESHOLD          69

#define MU_DIV_QR_THRESHOLD               1895
#define MU_DIVAPPR_Q_THRESHOLD            1895
#define MUPI_DIV_QR_THRESHOLD               73
#define MU_BDIV_QR_THRESHOLD              1589
#define MU_BDIV_Q_THRESHOLD               2172

#define POWM_SEC_TABLE  1,32,96,563,1221,1420

#define GET_STR_DC_THRESHOLD                13
#define GET_STR_PRECOMPUTE_THRESHOLD        21
#define SET_STR_DC_THRESHOLD               194
#define SET_STR_PRECOMPUTE_THRESHOLD       638

#define FAC_DSC_THRESHOLD                  208
#define FAC_ODD_THRESHOLD                  127

#define MATRIX22_STRASSEN_THRESHOLD         34
#define HGCD2_DIV1_METHOD                    3  /* 0.42% faster than 1 */
#define HGCD_THRESHOLD                      85
#define HGCD_APPR_THRESHOLD                 96
#define HGCD_REDUCE_THRESHOLD             4455
#define GCD_DC_THRESHOLD                   309
#define GCDEXT_DC_THRESHOLD                205
#define JACOBI_BASE_METHOD                   4  /* 20.66% faster than 1 */
