/* VIA Nano gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
2008, 2009 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8

/* 1600 MHz Nano 2xxx */

/* Generated by tuneup.c, 2009-11-25, gcc 4.3 */

#define MUL_TOOM22_THRESHOLD             20
#define MUL_TOOM33_THRESHOLD             66
#define MUL_TOOM44_THRESHOLD            315

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_TOOM2_THRESHOLD              38
#define SQR_TOOM3_THRESHOLD              77
#define SQR_TOOM4_THRESHOLD             577

#define MUL_FFT_TABLE  { 336, 800, 1856, 2816, 7168, 36864, 81920, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          528
#define MUL_FFT_THRESHOLD              4736

#define SQR_FFT_TABLE  { 400, 800, 1856, 3328, 9216, 20480, 81920, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          432
#define SQR_FFT_THRESHOLD              3456

#define MULLOW_BASECASE_THRESHOLD        15
#define MULLOW_DC_THRESHOLD               0  /* never mpn_mullow_basecase */
#define MULLOW_MUL_N_THRESHOLD         7653

#define MULMOD_BNM1_THRESHOLD            16

#define DC_DIV_QR_THRESHOLD              47
#define REDC_1_TO_REDC_2_THRESHOLD       17
#define REDC_2_TO_REDC_N_THRESHOLD      129

#define MATRIX22_STRASSEN_THRESHOLD      21
#define HGCD_THRESHOLD                  110
#define GCD_DC_THRESHOLD                465
#define GCDEXT_DC_THRESHOLD             693
#define JACOBI_BASE_METHOD                1

#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define MOD_1_1_THRESHOLD                 6
#define MOD_1_2_THRESHOLD                11
#define MOD_1_4_THRESHOLD                14
#define USE_PREINV_DIVREM_1               1  /* native */
#define USE_PREINV_MOD_1                  0
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always (native) */

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     22
#define SET_STR_DC_THRESHOLD            418
#define SET_STR_PRECOMPUTE_THRESHOLD   2017
