/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 2000 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8
#define BITS_PER_LONGINT 64
#define BITS_PER_INT 32
#define BITS_PER_SHORTINT 16
#define BITS_PER_CHAR 8

/* Generated by tuneup.c, 2000-11-11. */

#ifndef KARATSUBA_MUL_THRESHOLD
#define KARATSUBA_MUL_THRESHOLD     31
#endif
#ifndef TOOM3_MUL_THRESHOLD
#define TOOM3_MUL_THRESHOLD        141
#endif

#ifndef KARATSUBA_SQR_THRESHOLD
#define KARATSUBA_SQR_THRESHOLD     70
#endif
#ifndef TOOM3_SQR_THRESHOLD
#define TOOM3_SQR_THRESHOLD        108
#endif

#ifndef DC_THRESHOLD
#define DC_THRESHOLD               182
#endif

#ifndef FIB_THRESHOLD
#define FIB_THRESHOLD              196
#endif

#ifndef POWM_THRESHOLD
#define POWM_THRESHOLD             193
#endif

#ifndef GCD_ACCEL_THRESHOLD
#define GCD_ACCEL_THRESHOLD          3
#endif
#ifndef GCDEXT_THRESHOLD
#define GCDEXT_THRESHOLD             2
#endif

#ifndef FFT_MUL_TABLE
#define FFT_MUL_TABLE  { 656, 1376, 2880, 7424, 11264, 28672, 0 }
#endif
#ifndef FFT_MODF_MUL_THRESHOLD
#define FFT_MODF_MUL_THRESHOLD     720
#endif
#ifndef FFT_MUL_THRESHOLD
#define FFT_MUL_THRESHOLD         7680
#endif

#ifndef FFT_SQR_TABLE
#define FFT_SQR_TABLE  { 624, 1440, 3520, 7936, 15360, 36864, 0 }
#endif
#ifndef FFT_MODF_SQR_THRESHOLD
#define FFT_MODF_SQR_THRESHOLD     816
#endif
#ifndef FFT_SQR_THRESHOLD
#define FFT_SQR_THRESHOLD         6784
#endif
