/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002, 2004, 2005, 2008, 2009
Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 64
#define BYTES_PER_MP_LIMB 8

#define DIVEXACT_BY3_METHOD 0	/* override ../diveby3.asm */

/* 500 MHz 21164 (agnesi.math.su.se) */

/* Generated by tuneup.c, 2009-11-29, gcc 3.3 */

#define MUL_TOOM22_THRESHOLD             32
#define MUL_TOOM33_THRESHOLD             73
#define MUL_TOOM44_THRESHOLD            166

#define SQR_BASECASE_THRESHOLD            5
#define SQR_TOOM2_THRESHOLD              60
#define SQR_TOOM3_THRESHOLD             105
#define SQR_TOOM4_THRESHOLD             167

#define MUL_FFT_TABLE  { 304, 864, 1728, 3328, 9216, 28672, 147456, 327680, 0 }
#define MUL_FFT_MODF_THRESHOLD          432
#define MUL_FFT_THRESHOLD              3968

#define SQR_FFT_TABLE  { 400, 864, 1600, 3840, 9216, 28672, 114688, 327680, 0 }
#define SQR_FFT_MODF_THRESHOLD          376
#define SQR_FFT_THRESHOLD              3712

#define MULLO_BASECASE_THRESHOLD          0  /* always */
#define MULLO_DC_THRESHOLD              129
#define MULLO_MUL_N_THRESHOLD          7842

#define MULMOD_BNM1_THRESHOLD            16

#define DC_DIV_QR_THRESHOLD             112
#define DC_DIVAPPR_Q_THRESHOLD          396
#define DC_BDIV_QR_THRESHOLD            110
#define DC_BDIV_Q_THRESHOLD             315
#define BINV_NEWTON_THRESHOLD           889
#define REDC_1_TO_REDC_N_THRESHOLD      110

#define MATRIX22_STRASSEN_THRESHOLD      21
#define HGCD_THRESHOLD                  276
#define GCD_DC_THRESHOLD               1197
#define GCDEXT_DC_THRESHOLD             799
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD           0  /* preinv always */
#define DIVREM_1_UNNORM_THRESHOLD         0  /* always */
#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define MOD_1_1_THRESHOLD                 2
#define MOD_1_2_THRESHOLD                 6
#define MOD_1_4_THRESHOLD                30
#define USE_PREINV_DIVREM_1               1  /* preinv always */
#define USE_PREINV_MOD_1                  1  /* preinv always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD      MP_SIZE_T_MAX  /* never */

#define GET_STR_DC_THRESHOLD             18
#define GET_STR_PRECOMPUTE_THRESHOLD     23
#define SET_STR_DC_THRESHOLD           2797
#define SET_STR_PRECOMPUTE_THRESHOLD  10681
