/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2017 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 64
#define GMP_LIMB_BYTES 8

/* 900MHz Itanium2 (olympic.gmplib.org) */
/* FFT tuning limit = 0.5 M */
/* Generated by tuneup.c, 2017-02-19, gcc 4.2 */

#define MOD_1_1P_METHOD                      2
#define MOD_1_NORM_THRESHOLD                 0  /* always */
#define MOD_1_UNNORM_THRESHOLD               0  /* always */
#define MOD_1N_TO_MOD_1_1_THRESHOLD          8
#define MOD_1U_TO_MOD_1_1_THRESHOLD          6
#define MOD_1_1_TO_MOD_1_2_THRESHOLD        18
#define MOD_1_2_TO_MOD_1_4_THRESHOLD         0  /* never mpn_mod_1s_2p */
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD     13
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 1
#define DIV_QR_1_NORM_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD              12
#define DIVEXACT_1_THRESHOLD                 0  /* always (native) */
#define BMOD_1_TO_MOD_1_THRESHOLD        MP_SIZE_T_MAX  /* never */

#define DIV_1_VS_MUL_1_PERCENT             316

#define MUL_TOOM22_THRESHOLD                48
#define MUL_TOOM33_THRESHOLD                90
#define MUL_TOOM44_THRESHOLD               216
#define MUL_TOOM6H_THRESHOLD               327
#define MUL_TOOM8H_THRESHOLD               454

#define MUL_TOOM32_TO_TOOM43_THRESHOLD      97
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     153
#define MUL_TOOM42_TO_TOOM53_THRESHOLD     148
#define MUL_TOOM42_TO_TOOM63_THRESHOLD     153
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     226

#define SQR_BASECASE_THRESHOLD              11
#define SQR_TOOM2_THRESHOLD                 98
#define SQR_TOOM3_THRESHOLD                140
#define SQR_TOOM4_THRESHOLD                260
#define SQR_TOOM6_THRESHOLD                354
#define SQR_TOOM8_THRESHOLD                502

#define MULMID_TOOM42_THRESHOLD             99

#define MULMOD_BNM1_THRESHOLD               25
#define SQRMOD_BNM1_THRESHOLD               33

#define MUL_FFT_MODF_THRESHOLD             840  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    840, 5}, {     31, 6}, {     16, 5}, {     33, 6}, \
    {     17, 5}, {     35, 6}, {     37, 7}, {     19, 6}, \
    {     43, 7}, {     44, 8}, {     23, 7}, {     47, 8}, \
    {     43, 9}, {     23, 8}, {     51, 9}, {     27, 8}, \
    {     57, 9}, {     31, 8}, {     65, 9}, {     35, 8}, \
    {     71, 9}, {     43,10}, {     23, 9}, {     59,10}, \
    {     31, 9}, {     71,10}, {     39, 9}, {     83,10}, \
    {     47, 9}, {     99,10}, {     55, 9}, {    111,11}, \
    {     31,10}, {     63, 9}, {    127,10}, {     87,11}, \
    {     47,10}, {    111,11}, {     63,10}, {    143,11}, \
    {     79,10}, {    167,11}, {     95,10}, {    191,11}, \
    {    111,12}, {     63,11}, {    175,12}, {     95,11}, \
    {    207,13}, {   8192,14}, {  16384,15}, {  32768,16}, \
    {  65536,17}, { 131072,18}, { 262144,19}, { 524288,20}, \
    {1048576,21}, {2097152,22}, {4194304,23}, {8388608,24} }
#define MUL_FFT_TABLE3_SIZE 60
#define MUL_FFT_THRESHOLD                 8832

#define SQR_FFT_MODF_THRESHOLD             765  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    765, 5}, {     35, 6}, {     43, 7}, {     43, 8}, \
    {     43, 9}, {     23, 8}, {     49, 9}, {     27, 8}, \
    {     57, 9}, {     31, 8}, {     63, 9}, {     43,10}, \
    {     23, 9}, {     55,10}, {     31, 9}, {     71,10}, \
    {     39, 9}, {     83,10}, {     47, 9}, {     99,10}, \
    {     55,11}, {     31,10}, {     87,11}, {     47,10}, \
    {    111,12}, {     31,11}, {     63,10}, {    143,11}, \
    {     79,10}, {    167,11}, {    111,12}, {     63,11}, \
    {    159,12}, {     95,11}, {    207,13}, {   8192,14}, \
    {  16384,15}, {  32768,16}, {  65536,17}, { 131072,18}, \
    { 262144,19}, { 524288,20}, {1048576,21}, {2097152,22}, \
    {4194304,23}, {8388608,24} }
#define SQR_FFT_TABLE3_SIZE 46
#define SQR_FFT_THRESHOLD                 6784

#define MULLO_BASECASE_THRESHOLD            47
#define MULLO_DC_THRESHOLD                   0  /* never mpn_mullo_basecase */
#define MULLO_MUL_N_THRESHOLD            17561
#define SQRLO_BASECASE_THRESHOLD             0  /* always */
#define SQRLO_DC_THRESHOLD                 152
#define SQRLO_SQR_THRESHOLD              13555

#define DC_DIV_QR_THRESHOLD                 76
#define DC_DIVAPPR_Q_THRESHOLD             260
#define DC_BDIV_QR_THRESHOLD               116
#define DC_BDIV_Q_THRESHOLD                315

#define INV_MULMOD_BNM1_THRESHOLD           94
#define INV_NEWTON_THRESHOLD                17
#define INV_APPR_THRESHOLD                  21

#define BINV_NEWTON_THRESHOLD              296
#define REDC_1_TO_REDC_2_THRESHOLD           0  /* always */
#define REDC_2_TO_REDC_N_THRESHOLD         174

#define MU_DIV_QR_THRESHOLD               1470
#define MU_DIVAPPR_Q_THRESHOLD            1164
#define MUPI_DIV_QR_THRESHOLD                0  /* always */
#define MU_BDIV_QR_THRESHOLD              1685
#define MU_BDIV_Q_THRESHOLD               1787

#define POWM_SEC_TABLE  1,22,175,1896

#define GET_STR_DC_THRESHOLD                15
#define GET_STR_PRECOMPUTE_THRESHOLD        33
#define SET_STR_DC_THRESHOLD              1418
#define SET_STR_PRECOMPUTE_THRESHOLD      4091

#define FAC_DSC_THRESHOLD                 1547
#define FAC_ODD_THRESHOLD                   23

#define MATRIX22_STRASSEN_THRESHOLD         23
#define HGCD_THRESHOLD                     141
#define HGCD_APPR_THRESHOLD                147
#define HGCD_REDUCE_THRESHOLD             4455
#define GCD_DC_THRESHOLD                   710
#define GCDEXT_DC_THRESHOLD                505
#define JACOBI_BASE_METHOD                   2
