/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2000, 2001, 2002, 2003 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8

/* Generated by tuneup.c, 2003-10-01, gcc 2.96, itanium2, 1400MHz */

#define MUL_KARATSUBA_THRESHOLD          62
#define MUL_TOOM3_THRESHOLD             132

#define SQR_BASECASE_THRESHOLD            5
#define SQR_KARATSUBA_THRESHOLD         132
#define SQR_TOOM3_THRESHOLD             218

#define DIV_SB_PREINV_THRESHOLD           0  /* preinv always */
#define DIV_DC_THRESHOLD                 71
#define POWM_THRESHOLD                  619

#define GCD_ACCEL_THRESHOLD               3
#define GCDEXT_THRESHOLD                 81
#define JACOBI_BASE_METHOD                1

#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1  /* preinv always */
#define USE_PREINV_MOD_1                  1  /* preinv always */
#define DIVREM_2_THRESHOLD                0  /* preinv always */
#define DIVEXACT_1_THRESHOLD          MP_SIZE_T_MAX  /* never */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             13
#define GET_STR_PRECOMPUTE_THRESHOLD     19
#define SET_STR_THRESHOLD             24963

#define MUL_FFT_TABLE  { 656, 1568, 2368, 4864, 11264, 28672, 0 }
#define MUL_FFT_MODF_THRESHOLD          616
#define MUL_FFT_THRESHOLD              3968

#define SQR_FFT_TABLE  { 848, 1760, 2880, 6912, 15360, 28672, 0 }
#define SQR_FFT_MODF_THRESHOLD          712
#define SQR_FFT_THRESHOLD              3968
