/* PowerPC-64 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2008 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8

/* Generated by tuneup.c, 2008-10-28, gcc 4.0 */

#define MUL_KARATSUBA_THRESHOLD          16
#define MUL_TOOM3_THRESHOLD              66

#define SQR_BASECASE_THRESHOLD            5
#define SQR_KARATSUBA_THRESHOLD          32
#define SQR_TOOM3_THRESHOLD              65

#define MULLOW_BASECASE_THRESHOLD         0  /* always */
#define MULLOW_DC_THRESHOLD              56
#define MULLOW_MUL_N_THRESHOLD          303

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 36
#define POWM_THRESHOLD                  104

#define MATRIX22_STRASSEN_THRESHOLD      13
#define HGCD_THRESHOLD                  107
#define GCD_DC_THRESHOLD                269
#define GCDEXT_DC_THRESHOLD             324
#define JACOBI_BASE_METHOD                1

#define MOD_1_NORM_THRESHOLD              0  /* always */
#define MOD_1_UNNORM_THRESHOLD            0  /* always */
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always (native) */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD              7
#define GET_STR_PRECOMPUTE_THRESHOLD     17
#define SET_STR_DC_THRESHOLD            915
#define SET_STR_PRECOMPUTE_THRESHOLD   2031

#define MUL_FFT_TABLE  { 272, 672, 1856, 2816, 7168, 20480, 81920, 327680, 786432, 0 }
#define MUL_FFT_MODF_THRESHOLD          288
#define MUL_FFT_THRESHOLD              2432

#define SQR_FFT_TABLE  { 272, 672, 1600, 2816, 7168, 20480, 81920, 196608, 786432, 0 }
#define SQR_FFT_MODF_THRESHOLD          264
#define SQR_FFT_THRESHOLD              1920
