/* SPARC v9 32-bit gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002, 2004, 2009 Free Software
Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library.  If not, see http://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 32
#define BYTES_PER_MP_LIMB 4

/* Generated by tuneup.c, 2009-12-14, gcc 4.2 */

#define MUL_TOOM22_THRESHOLD             30
#define MUL_TOOM33_THRESHOLD             89
#define MUL_TOOM44_THRESHOLD            230

#define SQR_BASECASE_THRESHOLD            8
#define SQR_TOOM2_THRESHOLD              63
#define SQR_TOOM3_THRESHOLD              97
#define SQR_TOOM4_THRESHOLD             266

#define MUL_FFT_TABLE  { 304, 800, 1408, 3584, 10240, 24576, 98304, 393216, 0 }
#define MUL_FFT_MODF_THRESHOLD          264
#define MUL_FFT_THRESHOLD              1472

#define SQR_FFT_TABLE  { 336, 672, 1408, 3584, 10240, 24576, 98304, 393216, 0 }
#define SQR_FFT_MODF_THRESHOLD          232
#define SQR_FFT_THRESHOLD              2304

#define MULLO_BASECASE_THRESHOLD          0  /* always */
#define MULLO_DC_THRESHOLD              103
#define MULLO_MUL_N_THRESHOLD          2764

#define MULMOD_BNM1_THRESHOLD            13

#define DC_DIV_QR_THRESHOLD             116
#define DC_DIVAPPR_Q_THRESHOLD          387
#define DC_BDIV_QR_THRESHOLD            116
#define DC_BDIV_Q_THRESHOLD             272
#define INV_MULMOD_BNM1_THRESHOLD        58
#define INV_NEWTON_THRESHOLD            360
#define INV_APPR_THRESHOLD               13
#define BINV_NEWTON_THRESHOLD           348
#define REDC_1_TO_REDC_N_THRESHOLD       86

#define MATRIX22_STRASSEN_THRESHOLD      12
#define HGCD_THRESHOLD                  142
#define GCD_DC_THRESHOLD                630
#define GCDEXT_DC_THRESHOLD             416
#define JACOBI_BASE_METHOD                3

#define DIVREM_1_NORM_THRESHOLD           5
#define DIVREM_1_UNNORM_THRESHOLD         7
#define MOD_1_NORM_THRESHOLD              4
#define MOD_1_UNNORM_THRESHOLD            6
#define MOD_1_1_THRESHOLD                 5
#define MOD_1_2_THRESHOLD                 7
#define MOD_1_4_THRESHOLD                14
#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1
#define DIVREM_2_THRESHOLD                0  /* always */
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD      MP_SIZE_T_MAX  /* never */

#define GET_STR_DC_THRESHOLD             10
#define GET_STR_PRECOMPUTE_THRESHOLD     17
#define SET_STR_DC_THRESHOLD            527
#define SET_STR_PRECOMPUTE_THRESHOLD   1576
