/* x86/coreihwl gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 2019 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 32
#define GMP_LIMB_BYTES 4

/* 2900 MHz Core i5 Haswell */
/* FFT tuning limit = 0.5 */
/* Generated by tuneup.c, 2019-10-01, gcc 8.3 */

#define MOD_1_NORM_THRESHOLD                17
#define MOD_1_UNNORM_THRESHOLD              17
#define MOD_1N_TO_MOD_1_1_THRESHOLD         10
#define MOD_1U_TO_MOD_1_1_THRESHOLD          9
#define MOD_1_1_TO_MOD_1_2_THRESHOLD         0  /* never mpn_mod_1_1p */
#define MOD_1_2_TO_MOD_1_4_THRESHOLD        12
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD      5
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 1  /* 11.21% faster than 2 */
#define DIV_QR_1_NORM_THRESHOLD             13
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD           MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD                 0  /* always (native) */
#define BMOD_1_TO_MOD_1_THRESHOLD           21

#define DIV_1_VS_MUL_1_PERCENT             294

#define MUL_TOOM22_THRESHOLD                28
#define MUL_TOOM33_THRESHOLD               101
#define MUL_TOOM44_THRESHOLD               220
#define MUL_TOOM6H_THRESHOLD               318
#define MUL_TOOM8H_THRESHOLD               478

#define MUL_TOOM32_TO_TOOM43_THRESHOLD     101
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     163
#define MUL_TOOM42_TO_TOOM53_THRESHOLD     149
#define MUL_TOOM42_TO_TOOM63_THRESHOLD     146
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     142

#define SQR_BASECASE_THRESHOLD               0  /* always (native) */
#define SQR_TOOM2_THRESHOLD                 46
#define SQR_TOOM3_THRESHOLD                145
#define SQR_TOOM4_THRESHOLD                244
#define SQR_TOOM6_THRESHOLD                342
#define SQR_TOOM8_THRESHOLD                512

#define MULMID_TOOM42_THRESHOLD             98

#define MULMOD_BNM1_THRESHOLD               19
#define SQRMOD_BNM1_THRESHOLD               23

#define MUL_FFT_MODF_THRESHOLD             555  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    555, 5}, {     29, 6}, {     15, 5}, {     31, 6}, \
    {     29, 7}, {     15, 6}, {     33, 7}, {     17, 6}, \
    {     36, 7}, {     19, 6}, {     39, 7}, {     21, 6}, \
    {     43, 7}, {     23, 6}, {     47, 7}, {     29, 8}, \
    {     15, 7}, {     35, 8}, {     19, 7}, {     43, 8}, \
    {     23, 7}, {     49, 8}, {     27, 7}, {     55, 9}, \
    {     15, 8}, {     31, 7}, {     63, 8}, {     43, 9}, \
    {     23, 8}, {     55,10}, {     15, 9}, {     31, 8}, \
    {     67, 9}, {     39, 8}, {     83, 9}, {     47, 8}, \
    {     95, 9}, {     55,10}, {     31, 9}, {     79,10}, \
    {     47, 9}, {     95,11}, {     31,10}, {     63, 9}, \
    {    135,10}, {     79, 9}, {    159,10}, {     95, 9}, \
    {    191,11}, {     63,10}, {    159,11}, {     95,10}, \
    {    191,12}, {     63,11}, {    127,10}, {    255, 9}, \
    {    511,10}, {    287,11}, {    159,10}, {    335, 9}, \
    {    671,10}, {    351,11}, {    191,10}, {    415,11}, \
    {    223,12}, {   4096,13}, {   8192,14}, {  16384,15}, \
    {  32768,16} }
#define MUL_FFT_TABLE3_SIZE 69
#define MUL_FFT_THRESHOLD                 7424

#define SQR_FFT_MODF_THRESHOLD             530  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    530, 5}, {     29, 6}, {     15, 5}, {     31, 6}, \
    {     16, 5}, {     33, 6}, {     32, 7}, {     17, 6}, \
    {     36, 7}, {     19, 6}, {     40, 7}, {     29, 8}, \
    {     15, 7}, {     35, 8}, {     19, 7}, {     43, 8}, \
    {     23, 7}, {     49, 8}, {     27, 7}, {     57, 9}, \
    {     15, 8}, {     31, 7}, {     63, 8}, {     43, 9}, \
    {     23, 8}, {     55, 9}, {     31, 8}, {     67, 9}, \
    {     39, 8}, {     79, 9}, {     47, 8}, {     95, 9}, \
    {     55,10}, {     31, 9}, {     79,10}, {     47, 9}, \
    {     95,11}, {     31,10}, {     63, 9}, {    135,10}, \
    {     79, 9}, {    159,10}, {     95,11}, {     63,10}, \
    {    143, 9}, {    287,10}, {    159,11}, {     95,12}, \
    {     63,11}, {    127,10}, {    287,11}, {    159,10}, \
    {    367,11}, {    191,10}, {    415,12}, {   4096,13}, \
    {   8192,14}, {  16384,15}, {  32768,16} }
#define SQR_FFT_TABLE3_SIZE 59
#define SQR_FFT_THRESHOLD                 5568

#define MULLO_BASECASE_THRESHOLD            18
#define MULLO_DC_THRESHOLD                  40
#define MULLO_MUL_N_THRESHOLD            14709
#define SQRLO_BASECASE_THRESHOLD             0  /* always */
#define SQRLO_DC_THRESHOLD                 137
#define SQRLO_SQR_THRESHOLD              10821

#define DC_DIV_QR_THRESHOLD                 31
#define DC_DIVAPPR_Q_THRESHOLD             136
#define DC_BDIV_QR_THRESHOLD                98
#define DC_BDIV_Q_THRESHOLD                206

#define INV_MULMOD_BNM1_THRESHOLD           54
#define INV_NEWTON_THRESHOLD               123
#define INV_APPR_THRESHOLD                 125

#define BINV_NEWTON_THRESHOLD              296
#define REDC_1_TO_REDC_N_THRESHOLD          84

#define MU_DIV_QR_THRESHOLD               1652
#define MU_DIVAPPR_Q_THRESHOLD            1589
#define MUPI_DIV_QR_THRESHOLD                8
#define MU_BDIV_QR_THRESHOLD              1589
#define MU_BDIV_Q_THRESHOLD               1979

#define POWM_SEC_TABLE  1,11,114,321,1653

#define GET_STR_DC_THRESHOLD                10
#define GET_STR_PRECOMPUTE_THRESHOLD        16
#define SET_STR_DC_THRESHOLD               369
#define SET_STR_PRECOMPUTE_THRESHOLD      1005

#define FAC_DSC_THRESHOLD                  141
#define FAC_ODD_THRESHOLD                   29

#define MATRIX22_STRASSEN_THRESHOLD         21
#define HGCD2_DIV1_METHOD                    3  /* 7.07% faster than 1 */
#define HGCD_THRESHOLD                      70
#define HGCD_APPR_THRESHOLD                 86
#define HGCD_REDUCE_THRESHOLD             3524
#define GCD_DC_THRESHOLD                   584
#define GCDEXT_DC_THRESHOLD                465
#define JACOBI_BASE_METHOD                   1  /* 29.74% faster than 3 */
