/* gmp-mparam.h -- Compiler/machine parameter header file.

Copyright (C) 1991, 1993, 1994, 1999, 2000 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */

#define BITS_PER_MP_LIMB 64
#define BYTES_PER_MP_LIMB 8
#define BITS_PER_LONGINT 32
#define BITS_PER_INT 32
#define BITS_PER_SHORTINT 16
#define BITS_PER_CHAR 8

/* These values are for the R10000.  */

#if defined (__GNUC__)
/* Generated by tuneup.c, 2000-10-02. */

#ifndef KARATSUBA_MUL_THRESHOLD
#define KARATSUBA_MUL_THRESHOLD     16
#endif
#ifndef TOOM3_MUL_THRESHOLD
#define TOOM3_MUL_THRESHOLD         65
#endif

#ifndef KARATSUBA_SQR_THRESHOLD
#define KARATSUBA_SQR_THRESHOLD     14
#endif
#ifndef TOOM3_SQR_THRESHOLD
#define TOOM3_SQR_THRESHOLD         44
#endif

#ifndef BZ_THRESHOLD
#define BZ_THRESHOLD                13
#endif

#ifndef FIB_THRESHOLD
#define FIB_THRESHOLD               78
#endif

#ifndef POWM_THRESHOLD
#define POWM_THRESHOLD              80
#endif

#ifndef GCD_ACCEL_THRESHOLD
#define GCD_ACCEL_THRESHOLD         64
#endif
#ifndef GCDEXT_THRESHOLD
#define GCDEXT_THRESHOLD           140
#endif

#ifndef FFT_MUL_TABLE
#define FFT_MUL_TABLE  { 432, 928, 2368, 3840, 9216, 28672, 0 }
#endif
#ifndef FFT_MODF_MUL_THRESHOLD
#define FFT_MODF_MUL_THRESHOLD     448
#endif
#ifndef FFT_MUL_THRESHOLD
#define FFT_MUL_THRESHOLD         3968
#endif

#ifndef FFT_SQR_TABLE
#define FFT_SQR_TABLE  { 368, 864, 1728, 3328, 9216, 20480, 49152, 0 }
#endif
#ifndef FFT_MODF_SQR_THRESHOLD
#define FFT_MODF_SQR_THRESHOLD     232
#endif
#ifndef FFT_SQR_THRESHOLD
#define FFT_SQR_THRESHOLD         2944
#endif

#else /* ! __GNUC__ */

#define USE_MORE_MPN 1

/* Generated by tuneup.c, 2000-10-02. */
#ifndef KARATSUBA_MUL_THRESHOLD
#define KARATSUBA_MUL_THRESHOLD     18
#endif
#ifndef TOOM3_MUL_THRESHOLD
#define TOOM3_MUL_THRESHOLD        234
#endif

#ifndef KARATSUBA_SQR_THRESHOLD
#define KARATSUBA_SQR_THRESHOLD     16
#endif
#ifndef TOOM3_SQR_THRESHOLD
#define TOOM3_SQR_THRESHOLD         43
#endif

#ifndef BZ_THRESHOLD
#define BZ_THRESHOLD                63
#endif

#ifndef FIB_THRESHOLD
#define FIB_THRESHOLD               58
#endif

#ifndef POWM_THRESHOLD
#define POWM_THRESHOLD             144
#endif

#ifndef GCD_ACCEL_THRESHOLD
#define GCD_ACCEL_THRESHOLD        160
#endif
#ifndef GCDEXT_THRESHOLD
#define GCDEXT_THRESHOLD            42
#endif

#ifndef FFT_MUL_TABLE
#define FFT_MUL_TABLE  { 784, 1888, 5056, 7424, 21504, 45056, 0 }
#endif
#ifndef FFT_MODF_MUL_THRESHOLD
#define FFT_MODF_MUL_THRESHOLD    1232
#endif
#ifndef FFT_MUL_THRESHOLD
#define FFT_MUL_THRESHOLD        14848
#endif

#ifndef FFT_SQR_TABLE
#define FFT_SQR_TABLE  { 368, 864, 2624, 4352, 9216, 36864, 0 }
#endif
#ifndef FFT_MODF_SQR_THRESHOLD
#define FFT_MODF_SQR_THRESHOLD     784
#endif
#ifndef FFT_SQR_THRESHOLD
#define FFT_SQR_THRESHOLD         3712
#endif
#endif /* __GNUC__ */
