/* Intel P6/mmx gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991, 1993, 1994, 1999, 2000, 2001, 2002, 2003, 2004 Free Software
Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA. */


#define BITS_PER_MP_LIMB 32
#define BYTES_PER_MP_LIMB 4


/* NOTE: In a fat binary build SQR_KARATSUBA_THRESHOLD here cannot be more
   than the value in mpn/x86/p6/gmp-mparam.h.  The latter is used as a hard
   limit in mpn/x86/p6/sqr_basecase.asm.  */


/* 800MHz Pentium 3 */

/* Generated by tuneup.c, 2004-02-10, gcc 2.95 */

#define MUL_KARATSUBA_THRESHOLD          23
#define MUL_TOOM3_THRESHOLD              81

#define SQR_BASECASE_THRESHOLD            0  /* always (native) */
#define SQR_KARATSUBA_THRESHOLD          48
#define SQR_TOOM3_THRESHOLD              90

#define DIV_SB_PREINV_THRESHOLD           0  /* always */
#define DIV_DC_THRESHOLD                 76
#define POWM_THRESHOLD                  104

#define HGCD_SCHOENHAGE_THRESHOLD       174
#define GCD_ACCEL_THRESHOLD               3
#define GCD_SCHOENHAGE_THRESHOLD        885
#define GCDEXT_THRESHOLD                 37
#define JACOBI_BASE_METHOD                1

#define USE_PREINV_DIVREM_1               1
#define USE_PREINV_MOD_1                  1  /* native */
#define DIVREM_2_THRESHOLD                5
#define DIVEXACT_1_THRESHOLD              0  /* always */
#define MODEXACT_1_ODD_THRESHOLD          0  /* always */

#define GET_STR_DC_THRESHOLD             26
#define GET_STR_PRECOMPUTE_THRESHOLD     35
#define SET_STR_THRESHOLD              3524

#define MUL_FFT_TABLE  { 560, 1184, 1920, 5632, 14336, 40960, 0 }
#define MUL_FFT_MODF_THRESHOLD          488
#define MUL_FFT_THRESHOLD              3840

#define SQR_FFT_TABLE  { 560, 1184, 1920, 5632, 14336, 40960, 0 }
#define SQR_FFT_MODF_THRESHOLD          552
#define SQR_FFT_THRESHOLD              3840
