/* x86/core2 gmp-mparam.h -- Compiler/machine parameter header file.

Copyright 1991-2017 Free Software Foundation, Inc.

This file is part of the GNU MP Library.

The GNU MP Library is free software; you can redistribute it and/or modify
it under the terms of either:

  * the GNU Lesser General Public License as published by the Free
    Software Foundation; either version 3 of the License, or (at your
    option) any later version.

or

  * the GNU General Public License as published by the Free Software
    Foundation; either version 2 of the License, or (at your option) any
    later version.

or both in parallel, as here.

The GNU MP Library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received copies of the GNU General Public License and the
GNU Lesser General Public License along with the GNU MP Library.  If not,
see https://www.gnu.org/licenses/.  */

#define GMP_LIMB_BITS 32
#define GMP_LIMB_BYTES 4

/* 3000 MHz Core 2 (45nm) */
/* FFT tuning limit = 500000 */
/* Generated by tuneup.c, 2017-01-15, gcc 6.2 */

#define MOD_1_NORM_THRESHOLD             MP_SIZE_T_MAX  /* never */
#define MOD_1_UNNORM_THRESHOLD           MP_SIZE_T_MAX  /* never */
#define MOD_1N_TO_MOD_1_1_THRESHOLD         10
#define MOD_1U_TO_MOD_1_1_THRESHOLD          9
#define MOD_1_1_TO_MOD_1_2_THRESHOLD         0  /* never mpn_mod_1_1p */
#define MOD_1_2_TO_MOD_1_4_THRESHOLD         0  /* never mpn_mod_1s_2p */
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD      3
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 1
#define DIV_QR_1_NORM_THRESHOLD             17
#define DIV_QR_1_UNNORM_THRESHOLD        MP_SIZE_T_MAX  /* never */
#define DIV_QR_2_PI2_THRESHOLD           MP_SIZE_T_MAX  /* never */
#define DIVEXACT_1_THRESHOLD                 0  /* always (native) */
#define BMOD_1_TO_MOD_1_THRESHOLD           16

#define DIV_1_VS_MUL_1_PERCENT             290

#define MUL_TOOM22_THRESHOLD                24
#define MUL_TOOM33_THRESHOLD                93
#define MUL_TOOM44_THRESHOLD               214
#define MUL_TOOM6H_THRESHOLD               300
#define MUL_TOOM8H_THRESHOLD               462

#define MUL_TOOM32_TO_TOOM43_THRESHOLD      91
#define MUL_TOOM32_TO_TOOM53_THRESHOLD     145
#define MUL_TOOM42_TO_TOOM53_THRESHOLD      89
#define MUL_TOOM42_TO_TOOM63_THRESHOLD      95
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     130

#define SQR_BASECASE_THRESHOLD               0  /* always (native) */
#define SQR_TOOM2_THRESHOLD                 36
#define SQR_TOOM3_THRESHOLD                117
#define SQR_TOOM4_THRESHOLD                176
#define SQR_TOOM6_THRESHOLD                262
#define SQR_TOOM8_THRESHOLD                597

#define MULMID_TOOM42_THRESHOLD             64

#define MULMOD_BNM1_THRESHOLD               15
#define SQRMOD_BNM1_THRESHOLD               21

#define MUL_FFT_MODF_THRESHOLD             570  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    570, 5}, {     28, 6}, {     15, 5}, {     31, 6}, \
    {     28, 7}, {     15, 6}, {     33, 7}, {     17, 6}, \
    {     35, 7}, {     19, 6}, {     39, 7}, {     27, 8}, \
    {     15, 7}, {     35, 8}, {     19, 7}, {     41, 8}, \
    {     23, 7}, {     47, 8}, {     27, 9}, {     15, 8}, \
    {     31, 7}, {     63, 8}, {     43, 9}, {     23, 8}, \
    {     55,10}, {     15, 9}, {     31, 8}, {     67, 9}, \
    {     39, 8}, {     83, 9}, {     47, 8}, {     95, 9}, \
    {     55,10}, {     31, 9}, {     79,10}, {     47, 9}, \
    {     95,11}, {     31,10}, {     63, 9}, {    135,10}, \
    {     79, 9}, {    159, 8}, {    319, 9}, {    175,10}, \
    {    111,11}, {     63,10}, {    143, 9}, {    287,10}, \
    {    159,11}, {     95,12}, {     63,11}, {    127,10}, \
    {    255, 9}, {    543,10}, {    287,11}, {    159,10}, \
    {    319, 9}, {    639,10}, {    335, 9}, {    671,11}, \
    {    191,10}, {    383, 9}, {    767,10}, {    399, 9}, \
    {    799,10}, {    415,11}, {    223,12}, {   4096,13}, \
    {   8192,14}, {  16384,15}, {  32768,16} }
#define MUL_FFT_TABLE3_SIZE 71
#define MUL_FFT_THRESHOLD                 5760

#define SQR_FFT_MODF_THRESHOLD             472  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    472, 5}, {     28, 6}, {     15, 5}, {     31, 6}, \
    {     28, 7}, {     15, 6}, {     32, 7}, {     17, 6}, \
    {     35, 7}, {     19, 6}, {     39, 7}, {     29, 8}, \
    {     15, 7}, {     35, 8}, {     19, 7}, {     41, 8}, \
    {     23, 7}, {     49, 8}, {     27, 9}, {     15, 8}, \
    {     31, 7}, {     63, 8}, {     39, 9}, {     23, 8}, \
    {     51,10}, {     15, 9}, {     31, 8}, {     67, 9}, \
    {     39, 8}, {     79, 9}, {     55,10}, {     31, 9}, \
    {     79,10}, {     47, 9}, {     95,11}, {     31,10}, \
    {     63, 9}, {    127,10}, {     79, 9}, {    159,10}, \
    {     95,11}, {     63,10}, {    127, 9}, {    271,10}, \
    {    143, 9}, {    287, 8}, {    575, 7}, {   1215, 9}, \
    {    319,11}, {     95,10}, {    191,12}, {     63,11}, \
    {    127,10}, {    255, 9}, {    543, 8}, {   1087,10}, \
    {    287, 9}, {    575,11}, {    159, 9}, {    639,10}, \
    {    335, 8}, {   1343,10}, {    351, 9}, {    735,11}, \
    {    191,10}, {    383, 9}, {    799, 8}, {   1599,10}, \
    {    415,11}, {    223,12}, {   4096,13}, {   8192,14}, \
    {  16384,15}, {  32768,16} }
#define SQR_FFT_TABLE3_SIZE 74
#define SQR_FFT_THRESHOLD                 5312

#define MULLO_BASECASE_THRESHOLD             0  /* always */
#define MULLO_DC_THRESHOLD                  27
#define MULLO_MUL_N_THRESHOLD            11278
#define SQRLO_BASECASE_THRESHOLD             0  /* always */
#define SQRLO_DC_THRESHOLD                 142
#define SQRLO_SQR_THRESHOLD              10323

#define DC_DIV_QR_THRESHOLD                 19
#define DC_DIVAPPR_Q_THRESHOLD              53
#define DC_BDIV_QR_THRESHOLD                78
#define DC_BDIV_Q_THRESHOLD                182

#define INV_MULMOD_BNM1_THRESHOLD           46
#define INV_NEWTON_THRESHOLD                34
#define INV_APPR_THRESHOLD                  35

#define BINV_NEWTON_THRESHOLD              315
#define REDC_1_TO_REDC_N_THRESHOLD          80

#define MU_DIV_QR_THRESHOLD               1037
#define MU_DIVAPPR_Q_THRESHOLD             777
#define MUPI_DIV_QR_THRESHOLD                0  /* always */
#define MU_BDIV_QR_THRESHOLD              1442
#define MU_BDIV_Q_THRESHOLD               1524

#define POWM_SEC_TABLE  3,23,93,129,779,1378

#define GET_STR_DC_THRESHOLD                13
#define GET_STR_PRECOMPUTE_THRESHOLD        26
#define SET_STR_DC_THRESHOLD               434
#define SET_STR_PRECOMPUTE_THRESHOLD      1366

#define FAC_DSC_THRESHOLD                  187
#define FAC_ODD_THRESHOLD                   26

#define MATRIX22_STRASSEN_THRESHOLD         33
#define HGCD_THRESHOLD                     112
#define HGCD_APPR_THRESHOLD                156
#define HGCD_REDUCE_THRESHOLD             3014
#define GCD_DC_THRESHOLD                   365
#define GCDEXT_DC_THRESHOLD                298
#define JACOBI_BASE_METHOD                   4
